CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

INSERT INTO users (email, password)
VALUES (
  'test@test.com',
  '$2b$10$XK.pfVl.w7XkB.doUUTzzuvwi6s0n9HIDeoWz6ff0sz7qlCBWDQ1m'
)
ON CONFLICT (email) DO NOTHING;