CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

INSERT INTO users (email, password)
VALUES (
  'test@test.com',
  '$2b$10$TlJ0k8dVjP5jN1Y6xJjL2OWoV6x6rK6J6Q4K9l0j6gQzM7nWz2TgW'
)
ON CONFLICT (email) DO NOTHING;